### PR TITLE
Add a "ignore filter" feature and add an example in home page

### PR DESCRIPTION
**Pull request by mncorreialive**
#### Changes
 

- Added the "ignoreFilter" as new input in a ng-autocomplete component
- Added a new example in home page.

Fixes # (issue)

#### Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by cxspxr** [comment]
@gmerabishvili do you have any plans to merge it?

We, at IBM, would like to use your package (and are still using), don't want to create a fork of it

**Comment by cxspxr** [comment]
I would even go further and provide filterFunction that would accept the current data, query and would return the data. In case of ignoreFilter - just pass the function that would return the same results.

@gmerabishvili @mncorreialive what do you think?
Use-cases might be:
https://github.com/wouter2203/fuzzy-search
or any otther search algorithm implementation.

That would be only 10-20 lines change for the code of this PR, but the component would become much more versatile.

**Comment by mncorreialive** [comment]
Hi man! What's up?

I understood and believe what your ideia/implementation as a best implemention for this case. And I provides a null function to pass default filter method. No problem for me.

Obs: The only problem as wait @gmerabishvili review and merge our changes. I don't have relation with this lib/repostitory I am a developer needing a feature to solve default filter method hahahaha.

Send your pull request and I close this.

Best regards.

**Comment by gmerabishvili** [comment]
@mncorreialive @cxspxr  I think feat(filter): add possibility to specify custom filters #132

**Comment by cxspxr** [comment]
@gmerabishvili Yes, exactly. You can achieve ignoreFilter or any other filtering behavior with the usage of `filter` in #132 .  I believe this should be closed.

**Comment by gmerabishvili** [comment]
Hello, the feature is implemented. Please upgrade to latest 2.0.5 version. Thank you.

**Pull request closed without merging**
